name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to GitHub Pages
      id-token: write # to verify that the deployment source is legit
      issues: write # to open tickets upon broken links
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: deploy to GitHub Pages
        id: deploy
        uses: ./.github/actions/deploy-to-github-pages
